### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by jbrodriguez** [mrousavy/react-native-jsi-library-template#21]
Hi, you're doing cool stuff with JSI, i'm already using mmkv and vision-camera in some of my projects.

I want to create a jsi library, using this repo as the base.

I see some references here to fast-crypto in the code.

What would you suggest is the best way to consume the repo:
- fork and rename the project/references
- create a new rn library (probably with react-native-builder-bob), then copy paste from this repo

I'd appreciate your thoughts on this matter

**Comment by mrousavy** [comment]
Hey, yea I always just fork it and rename everything
